// lib/intervention-library.ts
//
// Seed library for the intervention engine. Dosed, evidence-graded interventions across three lanes
// (Nourish / Calm / Move), plus the finding→intervention map wired to findings-config.ts ids.
//
// Plain-language rule: `title` + `detail` read like an instruction a friend would give — specific,
// measurable, with a local (Chennai / South-Indian) example. The clinical phrasing lives only in
// `evidence.note`, which is what the report surfaces. Every intervention is a daily task; sub-7
// `daysPerWeek` items are spaced across the week by the selector. No supplements (they need a course,
// not a single day). Hydration is computed from body weight (see ComputeHydrationGlasses).

import type { Intervention, InterventionMap } from './intervention-schema'

const R = '2026-06-11' // evidence review date

export const INTERVENTIONS: Intervention[] = [
  // ── NOURISH ──────────────────────────────────────────────────────────
  {
    id: 'nr_soluble_fibre_oats', pillar: 'Nourish', title: 'Have a bowl of oats or porridge at breakfast',
    detail: 'About 4–5 tbsp (40 g) dry oats — as porridge or soaked overnight.',
    dose: { target: '>=3 g soluble fibre/day', metric: { amount: 3, unit: 'g', per: 'day' } },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'strong', note: '>=3 g/day oat beta-glucan lowers LDL by ~5% (recognised health claim).', source: 'Meta-analysis of 28 RCTs', reviewed: R },
    contraindications: [], rotationGroup: 'soluble_fibre', keystoneEligible: true, localeTags: ['IN', 'vegetarian'],
  },
  {
    id: 'nr_soluble_fibre_legumes', pillar: 'Nourish', title: 'Eat a bowl of dal or beans today',
    detail: 'One cupful of toor dal, moong dal, chana, rajma, or sundal.',
    dose: { target: '>=3 g soluble fibre/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'strong', note: 'Soluble fibre from legumes lowers LDL and steadies glucose.', reviewed: R },
    contraindications: [], rotationGroup: 'soluble_fibre', localeTags: ['IN', 'vegetarian'],
  },
  {
    id: 'nr_fibre_fruit', pillar: 'Nourish', title: 'Eat one whole fruit with the skin on',
    detail: 'Guava, apple, or pear — eaten whole, not juiced.',
    dose: { target: '1 whole fruit with skin/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Whole fruit adds soluble fibre and slows sugar absorption vs juice.', reviewed: R },
    contraindications: [], rotationGroup: 'soluble_fibre', localeTags: ['IN'],
  },
  {
    id: 'nr_iron_vitc', pillar: 'Nourish', title: 'Add lemon or tomato to one iron-rich meal',
    detail: 'Squeeze lemon over dal or keerai, or add tomato/amla.',
    dose: { target: '1 iron + vitamin-C meal/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'strong', note: 'Vitamin C keeps plant (non-heme) iron soluble, raising absorption.', source: 'Meta-analysis of ascorbic acid + non-heme iron', reviewed: R },
    contraindications: ['iron_overload'], rotationGroup: 'iron_intake', localeTags: ['IN', 'vegetarian'],
  },
  {
    id: 'nr_iron_foods', pillar: 'Nourish', title: 'Eat an iron-rich food today',
    detail: 'Cooked greens (murungai keerai, spinach), dal, chana, dates, jaggery, or pumpkin seeds.',
    dose: { target: '1 iron-rich food/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Regular dietary iron supports recovery of low iron stores.', reviewed: R },
    contraindications: ['iron_overload'], rotationGroup: 'iron_intake', localeTags: ['IN', 'vegetarian'],
  },
  {
    id: 'nr_iron_cookware', pillar: 'Nourish', title: 'Cook one dish in an iron kadai',
    detail: 'Cooking sambar or greens in iron adds absorbable iron to the food.',
    dose: { target: '1 dish in iron cookware/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Cooking in iron vessels measurably increases the iron content of food.', reviewed: R },
    contraindications: ['iron_overload'], rotationGroup: 'iron_intake', localeTags: ['IN'],
  },
  {
    id: 'nr_iron_avoid_tea', pillar: 'Nourish', title: 'Leave an hour between chai/coffee and iron-rich meals',
    detail: 'Tea and coffee tannins block iron absorption.',
    dose: { target: 'no tea/coffee with iron meals' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Polyphenols in tea/coffee inhibit non-heme iron absorption.', reviewed: R },
    contraindications: ['iron_overload'], rotationGroup: 'iron_intake', localeTags: ['IN'],
  },
  {
    id: 'nr_oily_fish', pillar: 'Nourish', title: 'Eat a palm-sized portion of oily fish today',
    detail: 'Sardines (mathi), mackerel (ayala), or salmon.',
    dose: { target: '2 servings oily fish / week' },
    intensity: 'gentle', effort: 1, daysPerWeek: 2,
    evidence: { grade: 'strong', note: 'Omega-3s lower triglycerides and have anti-inflammatory effects.', reviewed: R },
    contraindications: [], requires: ['fish'], allergens: ['fish'], rotationGroup: 'omega3',
  },
  {
    id: 'nr_flax_chia', pillar: 'Nourish', title: 'Stir 1 tbsp of ground flaxseed or chia into a meal',
    detail: 'Into curd, porridge, or a smoothie.',
    dose: { target: '1 tbsp ground flax/chia per day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Plant omega-3 (ALA) and fibre support lipids and inflammation.', reviewed: R },
    contraindications: [], rotationGroup: 'omega3', localeTags: ['IN', 'vegetarian'],
  },
  {
    id: 'nr_nuts', pillar: 'Nourish', title: 'Eat a small handful (~25 g) of unsalted nuts',
    detail: 'Groundnuts, almonds, or walnuts.',
    dose: { target: '~30 g unsalted nuts/day', metric: { amount: 30, unit: 'g', per: 'day' } },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Regular nut intake modestly lowers LDL and cardiovascular risk.', reviewed: R },
    contraindications: [], rotationGroup: 'healthy_fats', localeTags: ['IN', 'vegetarian'],
  },
  {
    id: 'nr_seeds', pillar: 'Nourish', title: 'Sprinkle a tablespoon of mixed seeds on a meal',
    detail: 'Pumpkin, sunflower, or sesame (ellu) seeds — minerals like magnesium and zinc.',
    dose: { target: '1 tbsp seeds/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Seeds are dense in magnesium, zinc, and healthy fats.', reviewed: R },
    contraindications: [], rotationGroup: 'micronutrient', localeTags: ['IN', 'vegetarian'],
  },
  {
    id: 'nr_zinc_foods', pillar: 'Nourish', title: 'Eat a zinc-rich food today',
    detail: 'Pumpkin seeds, sesame, cashews, chana, curd, or eggs.',
    dose: { target: '1 zinc-rich food/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Zinc supports immunity, skin, and wound healing; intake is often low on plant-based diets.', reviewed: R },
    contraindications: [], rotationGroup: 'micronutrient', localeTags: ['IN', 'vegetarian'],
  },
  {
    id: 'nr_swap_sugary_drink', pillar: 'Nourish', title: 'Skip sugary and aerated drinks today',
    detail: 'Swap soft drinks, packaged juice, or sweet coffee/tea for water or plain buttermilk (moru).',
    dose: { target: '<=0 sugary drinks today' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'strong', note: 'Sugary drinks are strongly linked to weight gain and diabetes risk.', reviewed: R },
    contraindications: [], rotationGroup: 'reduce_sugar', localeTags: ['IN'],
  },
  {
    id: 'nr_refined_carb_swap', pillar: 'Nourish', title: 'Swap white rice for millets or brown rice at one meal',
    detail: 'Ragi (kezhvaragu), kambu, thinai, samai, or hand-pounded / brown rice.',
    dose: { target: '1 whole-grain swap/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Whole grains improve the glycemic response and lower cardiometabolic risk.', reviewed: R },
    contraindications: [], rotationGroup: 'carb_quality', localeTags: ['IN', 'vegetarian'],
  },
  {
    id: 'nr_carb_protein_pairing', pillar: 'Nourish', title: 'Add dal, curd, or egg to your rice or roti meal',
    detail: 'Protein and veg alongside carbs keep blood sugar steadier.',
    dose: { target: 'protein + veg with carbs at one meal' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Protein and fibre alongside carbohydrate flatten the glucose rise.', reviewed: R },
    contraindications: [], rotationGroup: 'carb_quality', localeTags: ['IN'],
  },
  {
    id: 'nr_leafy_green', pillar: 'Nourish', title: 'Add a handful of cooked greens to one meal',
    detail: 'Murungai or arai keerai, spinach, or any greens.',
    dose: { target: '1 leafy-green serving/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'strong', note: 'Higher vegetable intake lowers cardiovascular and metabolic risk.', reviewed: R },
    contraindications: [], rotationGroup: 'vegetables', keystoneEligible: true, localeTags: ['IN', 'vegetarian'],
  },
  {
    id: 'nr_veg_half_plate', pillar: 'Nourish', title: 'Fill half your lunch plate with vegetables',
    detail: 'Poriyal, kootu, or salad before the rice.',
    dose: { target: '1 half-veg plate/day' },
    intensity: 'gentle', effort: 2, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'A higher vegetable share improves fibre, satiety and diet quality.', reviewed: R },
    contraindications: [], rotationGroup: 'vegetables', localeTags: ['IN', 'vegetarian'],
  },
  {
    id: 'nr_processed_snack_swap', pillar: 'Nourish', title: 'Swap one packet snack for a whole-food snack',
    detail: 'Roasted chana, sundal, nuts, or fruit instead of chips or biscuits.',
    dose: { target: '1 snack swap/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Lower ultra-processed intake is linked to less weight gain and metabolic risk.', reviewed: R },
    contraindications: [], rotationGroup: 'reduce_processed', localeTags: ['IN'],
  },
  {
    id: 'nr_protein_breakfast', pillar: 'Nourish', title: 'Eat a protein-rich breakfast',
    detail: '2 eggs, a bowl of sprouts, pesarattu, idli with extra sambar, curd, or paneer.',
    dose: { target: 'protein at breakfast' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Protein at breakfast improves satiety and steadies morning energy.', reviewed: R },
    contraindications: [], rotationGroup: 'protein', localeTags: ['IN'],
  },
  {
    id: 'nr_protein_each_meal', pillar: 'Nourish', title: 'Include a protein at each meal',
    detail: 'Dal, curd, paneer, eggs, fish, soya, or sprouts across the day.',
    dose: { target: 'protein at 3 meals/day' },
    intensity: 'gentle', effort: 2, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Even protein distribution supports muscle maintenance and appetite.', reviewed: R },
    contraindications: ['ckd'], rotationGroup: 'protein', localeTags: ['IN'],
  },
  {
    id: 'nr_vitd_food', pillar: 'Nourish', title: 'Eat a vitamin-D food today',
    detail: 'Egg yolk, fortified milk, mushrooms, or oily fish.',
    dose: { target: '1 vitamin-D food/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Dietary vitamin D supplements sunlight, especially when stores are low.', reviewed: R },
    contraindications: [], rotationGroup: 'vitamin_d', localeTags: ['IN'],
  },
  {
    id: 'nr_b12_foods', pillar: 'Nourish', title: 'Eat a B12 source today',
    detail: 'Milk, curd, or eggs.',
    dose: { target: '1 B12 source/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'B12 is needed for healthy red cells and nerves.', reviewed: R },
    contraindications: [], requires: ['dairy', 'egg'], rotationGroup: 'b_vitamins', localeTags: ['IN'],
  },
  {
    id: 'nr_magnesium_foods', pillar: 'Nourish', title: 'Eat a magnesium-rich food',
    detail: 'Pumpkin seeds, peanuts, greens, millets, or a small piece of dark chocolate.',
    dose: { target: '1 magnesium-rich food/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Magnesium supports muscle, sleep and glucose handling; many fall short.', reviewed: R },
    contraindications: [], rotationGroup: 'magnesium', localeTags: ['IN', 'vegetarian'],
  },
  {
    id: 'nr_calcium_foods', pillar: 'Nourish', title: 'Eat a calcium-rich food',
    detail: 'Milk or curd, ragi, sesame (ellu), or drumstick leaves.',
    dose: { target: '1 calcium source/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Adequate calcium supports bone health, important around menopause.', reviewed: R },
    contraindications: [], rotationGroup: 'calcium', localeTags: ['IN', 'vegetarian'],
  },
  {
    id: 'nr_colour_variety', pillar: 'Nourish', title: 'Add a vegetable or fruit colour you haven\'t had this week',
    detail: 'Different colours bring different micronutrients.',
    dose: { target: '1 new whole-food colour/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Dietary variety addresses broad micronutrient gaps better than single foods.', reviewed: R },
    contraindications: [], rotationGroup: 'variety', localeTags: ['IN', 'vegetarian'],
  },
  {
    id: 'nr_hydration', pillar: 'Nourish', title: 'Drink your daily water target',
    detail: 'Around 30 ml per kg of body weight; add 2–3 glasses on hot or active days. (Daily glass count is computed from your weight.)',
    dose: { target: '~30 ml per kg body weight / day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Adequate hydration supports energy, concentration and kidney function.', reviewed: R },
    contraindications: [], rotationGroup: 'hydration', localeTags: ['IN'],
  },

  // ── CALM (sleep · stress · mindfulness · connection) ───────────────────
  {
    id: 'cl_consistent_bedtime', pillar: 'Calm', title: 'Be in bed by your target time tonight',
    detail: 'Pick one bedtime and start winding down 30 minutes before.',
    dose: { target: 'consistent bedtime' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Regular sleep timing supports sleep depth and metabolic health.', reviewed: R },
    contraindications: [], rotationGroup: 'sleep_timing', keystoneEligible: true,
  },
  {
    id: 'cl_winddown', pillar: 'Calm', title: 'Start a 30-minute wind-down before bed',
    detail: 'Dim the lights, put work away, do something calm.',
    dose: { target: '30-min wind-down nightly' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'A consistent wind-down supports the evening fall in arousal and cortisol.', reviewed: R },
    contraindications: [], rotationGroup: 'sleep_winddown',
  },
  {
    id: 'cl_screens_off', pillar: 'Calm', title: 'Put screens away 30 minutes before bed',
    detail: 'Read or stretch instead of phone/TV.',
    dose: { target: 'no screens 30 min pre-bed' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Evening screen light suppresses melatonin and delays sleep.', reviewed: R },
    contraindications: [], rotationGroup: 'sleep_winddown',
  },
  {
    id: 'cl_caffeine_cutoff', pillar: 'Calm', title: 'No coffee or tea after 3 pm',
    detail: 'Caffeine lingers and disturbs sleep even if you fall asleep fine.',
    dose: { target: 'no caffeine after 3pm' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Late caffeine reduces sleep quality even when sleep onset feels normal.', reviewed: R },
    contraindications: [], rotationGroup: 'sleep_winddown', localeTags: ['IN'],
  },
  {
    id: 'cl_morning_daylight', pillar: 'Calm', title: 'Get 10 minutes of morning sunlight',
    detail: 'Step outside within an hour of waking — a walk or chai outdoors counts.',
    dose: { target: '10 min morning daylight/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Morning daylight anchors the circadian clock and supports mood and vitamin D.', reviewed: R },
    contraindications: [], rotationGroup: 'daylight', keystoneEligible: true, localeTags: ['IN'],
  },
  {
    id: 'cl_slow_breathing', pillar: 'Calm', title: 'Do 3 minutes of slow breathing',
    detail: 'Breathe in for 4 counts, out for 6 — about 6 breaths a minute.',
    dose: { target: '3 min slow breathing/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Slow breathing (~6/min) raises vagal/HRV tone and lowers acute stress.', reviewed: R },
    contraindications: [], rotationGroup: 'breathing', keystoneEligible: true,
  },
  {
    id: 'cl_breath_before_meal', pillar: 'Calm', title: 'Take 5 slow breaths before one meal',
    detail: 'A short pause that also slows eating.',
    dose: { target: '5 breaths before one meal/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'emerging', note: 'Brief pre-meal calming may reduce stress-driven eating.', reviewed: R },
    contraindications: [], rotationGroup: 'breathing',
  },
  {
    id: 'cl_meditation', pillar: 'Calm', title: 'Do a 10-minute meditation',
    detail: 'A guided session or quiet focus on your breath.',
    dose: { target: '10 min meditation/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Regular mindfulness meditation reduces stress and improves wellbeing.', reviewed: R },
    contraindications: [], rotationGroup: 'mindfulness',
  },
  {
    id: 'cl_restorative_break', pillar: 'Calm', title: 'Take one 10-minute phone-free break today',
    detail: 'Step outside, stretch, or sit quietly — no screen.',
    dose: { target: '1 restorative break/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Restorative breaks reduce stress load and mental fatigue.', reviewed: R },
    contraindications: [], rotationGroup: 'stress_breaks',
  },
  {
    id: 'cl_nature', pillar: 'Calm', title: 'Spend 15 minutes outdoors in green space',
    detail: 'A park, garden, or tree-lined street.',
    dose: { target: '15 min outdoors/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Time in nature lowers stress and lifts mood.', reviewed: R },
    contraindications: [], rotationGroup: 'stress_breaks',
  },
  {
    id: 'cl_social_connection', pillar: 'Calm', title: 'Reach out to one person today',
    detail: 'A call or message to someone you care about.',
    dose: { target: '1 meaningful contact/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Social connection is a robust protective factor for mood and wellbeing.', reviewed: R },
    contraindications: [], rotationGroup: 'connection',
  },
  {
    id: 'cl_share_meal', pillar: 'Calm', title: 'Share a meal with someone, phones away',
    detail: 'Eat with family, a colleague, or a friend without screens.',
    dose: { target: '1 shared meal/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Shared meals and connection support mood and steadier eating.', reviewed: R },
    contraindications: [], rotationGroup: 'connection', localeTags: ['IN'],
  },
  {
    id: 'cl_quality_time', pillar: 'Calm', title: 'Spend 15 minutes of real time with someone',
    detail: 'A walk, a chat, or a shared activity — fully present, no phone.',
    dose: { target: '15 min quality time/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Quality social time buffers stress and supports wellbeing.', reviewed: R },
    contraindications: [], rotationGroup: 'connection',
  },
  {
    id: 'cl_gratitude', pillar: 'Calm', title: 'Write down 3 specific good things from today',
    detail: 'What happened, and why it was good.',
    dose: { target: '3 notes/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'emerging', note: 'Brief gratitude practices show small positive effects on mood.', reviewed: R },
    contraindications: [], rotationGroup: 'mood',
  },
  {
    id: 'cl_alcohol_free_day', pillar: 'Calm', title: 'Keep today alcohol-free',
    detail: 'Aim for two dry days over the weekend — your liver and sleep both recover.',
    dose: { target: '2 alcohol-free days / week (weekend)' },
    intensity: 'gentle', effort: 1, daysPerWeek: 2, preferredDays: ['Sat', 'Sun'],
    evidence: { grade: 'strong', note: 'Regular alcohol-free days improve liver enzymes, sleep quality, and long-term risk.', reviewed: R },
    contraindications: [], rotationGroup: 'alcohol',
  },

  // ── MOVE ──────────────────────────────────────────────────────────────
  {
    id: 'mv_postmeal_walk', pillar: 'Move', title: 'Walk for 10 minutes after your biggest meal',
    detail: 'A gentle stroll within 30 minutes of eating.',
    dose: { target: '>=1 post-meal walk/day', metric: { amount: 1, unit: 'walk', per: 'day' } },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'strong', note: 'Walking soon after eating blunts the postprandial glucose rise; even ~10 min helps.', source: 'Meta-analyses of postprandial exercise', reviewed: R },
    contraindications: [], rotationGroup: 'glucose_movement', keystoneEligible: true, localeTags: ['IN'],
  },
  {
    id: 'mv_postmeal_walk_each', pillar: 'Move', title: 'Take a 10-minute walk after two meals today',
    detail: 'For example, after lunch and after dinner.',
    dose: { target: '2 short walks/day', metric: { amount: 2, unit: 'walk', per: 'day' } },
    intensity: 'gentle', effort: 2, daysPerWeek: 7,
    evidence: { grade: 'strong', note: 'Splitting walking across meals improves 24-h glucose more than one long walk.', reviewed: R },
    contraindications: [], rotationGroup: 'glucose_movement', localeTags: ['IN'],
  },
  {
    id: 'mv_morning_stretch', pillar: 'Move', title: 'Do a 5-minute stretch right after waking',
    detail: 'Neck, shoulders, back, and legs — the same simple routine each morning.',
    dose: { target: '5-min morning stretch/day' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'A short daily mobility routine eases stiffness and supports staying active.', reviewed: R },
    contraindications: [], rotationGroup: 'mobility',
  },
  {
    id: 'mv_sitting_breaks', pillar: 'Move', title: 'Stand or walk for 2–3 minutes every hour you sit',
    detail: 'Break up long stretches of sitting through the day.',
    dose: { target: 'hourly sitting break' },
    intensity: 'gentle', effort: 1, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Interrupting prolonged sitting improves post-meal glucose and circulation.', reviewed: R },
    contraindications: [], rotationGroup: 'sedentary_breaks',
  },
  {
    id: 'mv_aerobic_150', pillar: 'Move', title: 'Take a brisk 30-minute walk',
    detail: '"Brisk" = breathing harder but still able to talk. Build up over the weeks.',
    dose: {
      target: '150 min moderate activity / week', metric: { amount: 150, unit: 'min', per: 'week' },
      baselineKey: 'activityMinutesPerWeek',
      ladder: [
        { phase: 'foundation', dailyAction: '15-min brisk walk', weeklyTarget: '~75 min' },
        { phase: 'build', dailyAction: '25-min brisk walk', weeklyTarget: '~125 min' },
        { phase: 'consolidate', dailyAction: '30-min brisk walk', weeklyTarget: '150+ min' },
      ],
    },
    intensity: 'moderate', effort: 2, daysPerWeek: 5,
    evidence: { grade: 'strong', note: 'WHO advises 150–300 min/week; improves insulin sensitivity, BP and lipids.', source: 'WHO Physical Activity Guidelines 2020', reviewed: R },
    contraindications: ['cardiac_redflag'], fallbackId: 'mv_postmeal_walk', rotationGroup: 'aerobic_base', keystoneEligible: true,
  },
  {
    id: 'mv_hiit', pillar: 'Move', title: 'Do a 20-minute interval workout',
    detail: 'Alternate ~1 minute of hard effort with 2 minutes easy — only if you feel well and have no red flags.',
    dose: { target: '1–2 interval sessions / week' },
    intensity: 'vigorous', effort: 3, daysPerWeek: 2,
    evidence: { grade: 'moderate', note: 'Interval training improves cardiorespiratory fitness and glycemic control.', reviewed: R },
    contraindications: ['anemia', 'cardiac_redflag', 'uncontrolled_htn', 'referral_open', 'pregnancy', 'mobility_limited'],
    fallbackId: 'mv_aerobic_150', rotationGroup: 'aerobic_base',
  },
  {
    id: 'mv_strength_2x', pillar: 'Move', title: 'Do a strength session',
    detail: 'Work the major muscles — squats, lunges, rows, presses; use weights if you have them.',
    dose: {
      target: '2 strength sessions / week',
      ladder: [
        { phase: 'foundation', dailyAction: 'a short, easy strength session', daysPerWeek: 1 },
        { phase: 'build', dailyAction: 'a full strength session', daysPerWeek: 2 },
        { phase: 'consolidate', dailyAction: 'a full strength session', daysPerWeek: 2 },
      ],
    },
    intensity: 'moderate', effort: 2, daysPerWeek: 2,
    evidence: { grade: 'strong', note: 'Resistance training preserves muscle and bone and improves insulin sensitivity.', source: 'WHO 2020 (muscle-strengthening 2+ days/week)', reviewed: R },
    contraindications: ['cardiac_redflag', 'uncontrolled_htn'], fallbackId: 'mv_bodyweight', rotationGroup: 'strength',
  },
  {
    id: 'mv_bodyweight', pillar: 'Move', title: 'Do a 10-minute bodyweight workout',
    detail: 'Squats, wall push-ups, and calf raises — no equipment needed.',
    dose: { target: '2 sessions / week' },
    intensity: 'gentle', effort: 2, daysPerWeek: 2,
    evidence: { grade: 'moderate', note: 'Bodyweight resistance work builds strength accessibly, including for beginners.', reviewed: R },
    contraindications: [], rotationGroup: 'strength', localeTags: ['IN'],
  },
  {
    id: 'mv_yoga', pillar: 'Move', title: 'Do 15 minutes of yoga or surya namaskar',
    detail: 'A simple flow for strength, flexibility, and calm.',
    dose: { target: '15-min yoga session' },
    intensity: 'gentle', effort: 2, daysPerWeek: 3,
    evidence: { grade: 'moderate', note: 'Yoga improves flexibility, balance and stress, and counts toward activity.', reviewed: R },
    contraindications: [], rotationGroup: 'holistic', localeTags: ['IN'],
  },
  {
    id: 'mv_steps_7k', pillar: 'Move', title: 'Build toward 7,000–8,000 steps a day',
    detail: 'Small additions — a longer route, the stairs, a call taken walking.',
    dose: {
      target: '7,000–8,000 steps / day', metric: { amount: 7500, unit: 'steps', per: 'day' }, baselineKey: 'stepsPerDay',
      ladder: [
        { phase: 'foundation', dailyAction: 'add 1,500 steps to your usual day' },
        { phase: 'build', dailyAction: 'reach ~6,000 steps' },
        { phase: 'consolidate', dailyAction: 'hold 7,000–8,000 steps' },
      ],
    },
    intensity: 'gentle', effort: 2, daysPerWeek: 7,
    evidence: { grade: 'moderate', note: 'Step counts around 7–8k/day are associated with markedly lower mortality.', reviewed: R },
    contraindications: [], rotationGroup: 'daily_steps', keystoneEligible: true,
  },
]

// ── Keyed lookup (O(1) access for the engine) ─────────────────────────────
export const INTERVENTION_LIBRARY: Record<string, Intervention> = Object.fromEntries(
  INTERVENTIONS.map(iv => [iv.id, iv]),
)

// ── Finding → intervention map (keyed to findings-config.ts ids) ──────────
export const INTERVENTION_MAP: InterventionMap = {
  insulin_resistance: [
    { interventionId: 'mv_postmeal_walk', relevance: 1.0, grade: 'strong' },
    { interventionId: 'mv_aerobic_150', relevance: 0.8 },
    { interventionId: 'nr_carb_protein_pairing', relevance: 0.7 },
    { interventionId: 'nr_refined_carb_swap', relevance: 0.6 },
    { interventionId: 'mv_strength_2x', relevance: 0.6 },
    { interventionId: 'mv_sitting_breaks', relevance: 0.5 },
    { interventionId: 'mv_steps_7k', relevance: 0.5 },
  ],
  metabolic_syndrome: [
    { interventionId: 'mv_aerobic_150', relevance: 0.9, grade: 'strong' },
    { interventionId: 'mv_postmeal_walk', relevance: 0.8 },
    { interventionId: 'nr_swap_sugary_drink', relevance: 0.7, grade: 'strong' },
    { interventionId: 'nr_soluble_fibre_oats', relevance: 0.6 },
    { interventionId: 'mv_strength_2x', relevance: 0.6 },
    { interventionId: 'mv_steps_7k', relevance: 0.6 },
  ],
  diabetes_risk: [
    { interventionId: 'mv_postmeal_walk', relevance: 0.9, grade: 'strong' },
    { interventionId: 'mv_aerobic_150', relevance: 0.9, grade: 'strong' },
    { interventionId: 'nr_swap_sugary_drink', relevance: 0.8, grade: 'strong' },
    { interventionId: 'nr_soluble_fibre_oats', relevance: 0.7 },
    { interventionId: 'nr_refined_carb_swap', relevance: 0.6 },
    { interventionId: 'mv_steps_7k', relevance: 0.6 },
  ],
  pcos_suggestive: [
    { interventionId: 'mv_aerobic_150', relevance: 0.8 },
    { interventionId: 'mv_strength_2x', relevance: 0.7 },
    { interventionId: 'mv_postmeal_walk', relevance: 0.7 },
    { interventionId: 'nr_refined_carb_swap', relevance: 0.6 },
    { interventionId: 'nr_soluble_fibre_oats', relevance: 0.6 },
  ],
  dyslipidemia: [
    { interventionId: 'nr_soluble_fibre_oats', relevance: 0.9, grade: 'strong' },
    { interventionId: 'nr_soluble_fibre_legumes', relevance: 0.9, grade: 'strong' },
    { interventionId: 'nr_nuts', relevance: 0.7 },
    { interventionId: 'nr_oily_fish', relevance: 0.7 },
    { interventionId: 'mv_aerobic_150', relevance: 0.6 },
  ],
  cardiometabolic_risk: [
    { interventionId: 'nr_soluble_fibre_oats', relevance: 0.8, grade: 'strong' },
    { interventionId: 'mv_aerobic_150', relevance: 0.7 },
    { interventionId: 'nr_nuts', relevance: 0.6 },
    { interventionId: 'nr_oily_fish', relevance: 0.6 },
  ],
  apob_ldl_discordance: [
    { interventionId: 'nr_soluble_fibre_oats', relevance: 0.8, grade: 'strong' },
    { interventionId: 'nr_oily_fish', relevance: 0.6 },
    { interventionId: 'nr_nuts', relevance: 0.6 },
    { interventionId: 'mv_aerobic_150', relevance: 0.6 },
  ],
  statin_ldl_control: [
    { interventionId: 'nr_soluble_fibre_oats', relevance: 0.7 },
    { interventionId: 'mv_aerobic_150', relevance: 0.5 },
  ],
  iron_deficiency: [
    { interventionId: 'nr_iron_vitc', relevance: 1.0, grade: 'strong' },
    { interventionId: 'nr_iron_foods', relevance: 0.9 },
    { interventionId: 'nr_iron_avoid_tea', relevance: 0.7 },
    { interventionId: 'nr_iron_cookware', relevance: 0.6 },
  ],
  mcv_rdw_early_deficiency: [
    { interventionId: 'nr_iron_vitc', relevance: 0.7 },
    { interventionId: 'nr_iron_foods', relevance: 0.7 },
  ],
  inflammation: [
    { interventionId: 'nr_oily_fish', relevance: 0.7 },
    { interventionId: 'nr_flax_chia', relevance: 0.6 },
    { interventionId: 'nr_colour_variety', relevance: 0.6 },
    { interventionId: 'nr_processed_snack_swap', relevance: 0.6 },
    { interventionId: 'mv_aerobic_150', relevance: 0.5 },
    { interventionId: 'cl_slow_breathing', relevance: 0.5 },
  ],
  anemia_inflammatory: [
    { interventionId: 'nr_oily_fish', relevance: 0.5 },
    { interventionId: 'nr_colour_variety', relevance: 0.5 },
  ],
  vitamin_d_low: [
    { interventionId: 'cl_morning_daylight', relevance: 0.8 },
    { interventionId: 'nr_vitd_food', relevance: 0.8 },
  ],
  b12_folate_low: [
    { interventionId: 'nr_b12_foods', relevance: 0.8 },
  ],
  multi_nutrient_gap: [
    { interventionId: 'nr_colour_variety', relevance: 0.9 },
    { interventionId: 'nr_leafy_green', relevance: 0.7 },
    { interventionId: 'nr_seeds', relevance: 0.7 },
    { interventionId: 'nr_zinc_foods', relevance: 0.6 },
    { interventionId: 'nr_iron_foods', relevance: 0.5 },
  ],
  magnesium_low: [
    { interventionId: 'nr_magnesium_foods', relevance: 0.9 },
    { interventionId: 'nr_seeds', relevance: 0.6 },
  ],
  liver_stress: [
    { interventionId: 'nr_swap_sugary_drink', relevance: 0.7 },
    { interventionId: 'nr_refined_carb_swap', relevance: 0.7 },
    { interventionId: 'mv_aerobic_150', relevance: 0.7 },
  ],
  liver_fibrosis_risk: [
    { interventionId: 'mv_aerobic_150', relevance: 0.8 },
    { interventionId: 'nr_swap_sugary_drink', relevance: 0.6 },
    { interventionId: 'nr_refined_carb_swap', relevance: 0.6 },
    { interventionId: 'mv_strength_2x', relevance: 0.5 },
  ],
  risky_alcohol: [
    { interventionId: 'cl_alcohol_free_day', relevance: 1.0, grade: 'strong' },
  ],
  alcohol_liver_ratio: [
    { interventionId: 'cl_alcohol_free_day', relevance: 0.9, grade: 'strong' },
  ],
  high_stress: [
    { interventionId: 'cl_slow_breathing', relevance: 1.0 },
    { interventionId: 'cl_meditation', relevance: 0.8 },
    { interventionId: 'cl_restorative_break', relevance: 0.8 },
    { interventionId: 'cl_nature', relevance: 0.6 },
    { interventionId: 'mv_yoga', relevance: 0.6 },
    { interventionId: 'cl_quality_time', relevance: 0.5 },
    { interventionId: 'cl_breath_before_meal', relevance: 0.5 },
  ],
  adrenal_stress: [
    { interventionId: 'cl_meditation', relevance: 0.7 },
    { interventionId: 'cl_slow_breathing', relevance: 0.7 },
    { interventionId: 'cl_winddown', relevance: 0.7 },
    { interventionId: 'cl_restorative_break', relevance: 0.6 },
  ],
  poor_sleep: [
    { interventionId: 'cl_consistent_bedtime', relevance: 0.9 },
    { interventionId: 'cl_screens_off', relevance: 0.8 },
    { interventionId: 'cl_winddown', relevance: 0.7 },
    { interventionId: 'cl_caffeine_cutoff', relevance: 0.6 },
    { interventionId: 'cl_morning_daylight', relevance: 0.6 },
    { interventionId: 'cl_meditation', relevance: 0.5 },
  ],
  low_wellbeing: [
    { interventionId: 'cl_social_connection', relevance: 0.8 },
    { interventionId: 'cl_quality_time', relevance: 0.7 },
    { interventionId: 'cl_nature', relevance: 0.7 },
    { interventionId: 'mv_aerobic_150', relevance: 0.6 },
    { interventionId: 'cl_share_meal', relevance: 0.6 },
    { interventionId: 'cl_meditation', relevance: 0.6 },
    { interventionId: 'mv_yoga', relevance: 0.5 },
    { interventionId: 'cl_gratitude', relevance: 0.5 },
  ],
  insufficient_activity: [
    { interventionId: 'mv_aerobic_150', relevance: 0.9, grade: 'strong' },
    { interventionId: 'mv_steps_7k', relevance: 0.9 },
    { interventionId: 'mv_postmeal_walk', relevance: 0.7 },
    { interventionId: 'mv_sitting_breaks', relevance: 0.6 },
    { interventionId: 'mv_yoga', relevance: 0.5 },
    { interventionId: 'mv_morning_stretch', relevance: 0.5 },
  ],
  diet_quality: [
    { interventionId: 'nr_leafy_green', relevance: 0.9, grade: 'strong' },
    { interventionId: 'nr_processed_snack_swap', relevance: 0.8 },
    { interventionId: 'nr_veg_half_plate', relevance: 0.7 },
    { interventionId: 'nr_colour_variety', relevance: 0.7 },
    { interventionId: 'nr_fibre_fruit', relevance: 0.6 },
  ],
  low_testosterone_men: [
    { interventionId: 'mv_strength_2x', relevance: 0.8 },
    { interventionId: 'mv_aerobic_150', relevance: 0.6 },
    { interventionId: 'mv_hiit', relevance: 0.5 },
  ],
  menopausal_transition: [
    { interventionId: 'mv_strength_2x', relevance: 0.8 },
    { interventionId: 'nr_calcium_foods', relevance: 0.7 },
    { interventionId: 'mv_aerobic_150', relevance: 0.6 },
    { interventionId: 'mv_yoga', relevance: 0.6 },
    { interventionId: 'mv_morning_stretch', relevance: 0.5 },
  ],
  dehydration_pattern: [
    { interventionId: 'nr_hydration', relevance: 0.9 },
  ],
  electrolyte: [
    { interventionId: 'nr_hydration', relevance: 0.5 },
  ],
  high_androgen_women: [
    { interventionId: 'mv_aerobic_150',        relevance: 0.8, grade: 'strong' },
    { interventionId: 'mv_strength_2x',         relevance: 0.7 },
    { interventionId: 'nr_refined_carb_swap',   relevance: 0.7 },
    { interventionId: 'mv_postmeal_walk',        relevance: 0.6 },
    { interventionId: 'nr_soluble_fibre_oats',  relevance: 0.5 },
  ],
  low_shbg: [
    { interventionId: 'nr_refined_carb_swap',   relevance: 0.8 },
    { interventionId: 'mv_aerobic_150',          relevance: 0.7 },
    { interventionId: 'mv_strength_2x',          relevance: 0.6 },
    { interventionId: 'nr_soluble_fibre_oats',  relevance: 0.5 },
  ],
  hyperuricemia: [
    { interventionId: 'nr_hydration',           relevance: 0.9 },
    { interventionId: 'nr_refined_carb_swap',   relevance: 0.7 },
    { interventionId: 'mv_aerobic_150',          relevance: 0.5 },
  ],
  anion_gap_elevated: [
    { interventionId: 'nr_hydration',           relevance: 0.5 },
  ],
  allergy_atopy: [
    { interventionId: 'nr_colour_variety',      relevance: 0.7 },
    { interventionId: 'nr_veg_half_plate',      relevance: 0.6 },
    { interventionId: 'nr_oily_fish',           relevance: 0.5 },
  ],
  low_ag_ratio: [
    { interventionId: 'nr_veg_half_plate',      relevance: 0.6 },
    { interventionId: 'nr_colour_variety',      relevance: 0.5 },
  ],
}
